### PR TITLE
Support listen to specify sock file

### PR DESCRIPTION
**Pull request by LeiZhang-Hunter**

### CODE REVIEW

**Comment by jmjoy** [comment]
Fixed socket file name will cause problems when reloading php-fpm (kill -USR2), which is why the socket name is randomly generated.

**Comment by LeiZhang-Hunter** [comment]
> Fixed socket file name will cause problems when reloading php-fpm (kill -USR2), which is why the socket name is randomly generated.

如果fpm 不加-F，会导致没有任何程序监听套接字，我自己做了一个agent 去监听这个套接字，所以说需要固定一下套接字

**Comment by wu-sheng** [comment]
@LeiZhang-Hunter If you need to discuss in Chinese, Slack CN is a good place. In the PR context, please keep in En.

**Comment by LeiZhang-Hunter** [comment]
> @LeiZhang-Hunter If you need to discuss in Chinese, Slack CN is a good place. In the PR context, please keep in En.



> Fixed socket file name will cause problems when reloading php-fpm (kill -USR2), which is why the socket name is randomly generated.

If I don't add the -F option to php-fpm, then no process will listen to .sock, so I want to fix the .sock path and write my own program to listen

**Comment by LeiZhang-Hunter** [comment]
> @LeiZhang-Hunter If you need to discuss in Chinese, Slack CN is a good place. In the PR context, please keep in En.

If I don't add the -F option to php-fpm, then no process will listen to .sock, so I want to fix the .sock path and write my own program to listen

**Comment by heyanlong** [comment]
I don't think fixed socket file names are a smart idea.

**Comment by jmjoy** [comment]
> If I don't add the -F option to php-fpm, then no process will listen to .sock, so I want to fix the .sock path and write my own program to listen

Now it is not possible to run php-fpm in daemon mode, which will cause the skywalking agnet process to exit immediately, 
automatically delete the socket file when the process exits, which has nothing to do with the name of the socket file.

If daemon mode is required, skywalking agnet needs to be a separate process, and php-fpm no longer forks. This feature can be added later.

**Comment by LeiZhang-Hunter** [comment]
> > If I don't add the -F option to php-fpm, then no process will listen to .sock, so I want to fix the .sock path and write my own program to listen
> 
> Now it is not possible to run php-fpm in daemon mode, which will cause the skywalking agnet process to exit immediately, automatically delete the socket file when the process exits, which has nothing to do with the name of the socket file.
> 
> If daemon mode is required, skywalking agnet needs to be a separate process, and php-fpm no longer forks. This feature can be added later.

I have made this agent in C++. Now I need to monitor the .sock file. I think skywalking-php should provide this capability so that users can monitor their own sockets. It doesn't matter if skywalking-php is deleted. I can monitor it myself. Now after skywalking is deleted, as long as I create the corresponding sock file, it will still be sent to me.

**Comment by jmjoy** [comment]
> I have made this agent in C++. Now I need to monitor the .sock file. I think skywalking-php should provide this capability so that users can monitor their own sockets. It doesn't matter if skywalking-php is deleted. I can monitor it myself. Now after skywalking is deleted, as long as I create the corresponding sock file, it will still be sent to me.

This is great, but I think a better approach would be to add a new config to disable forking agnet processes and custom socket files.

**Comment by LeiZhang-Hunter** [comment]
> > I have made this agent in C++. Now I need to monitor the .sock file. I think skywalking-php should provide this capability so that users can monitor their own sockets. It doesn't matter if skywalking-php is deleted. I can monitor it myself. Now after skywalking is deleted, as long as I create the corresponding sock file, it will still be sent to me.
> 
> This is great, but I think a better approach would be to add a new config to disable forking agnet processes and custom socket files.

OK, I'll change it.

**Comment by LeiZhang-Hunter** [comment]
> > I have made this agent in C++. Now I need to monitor the .sock file. I think skywalking-php should provide this capability so that users can monitor their own sockets. It doesn't matter if skywalking-php is deleted. I can monitor it myself. Now after skywalking is deleted, as long as I create the corresponding sock file, it will still be sent to me.
> 
> This is great, but I think a better approach would be to add a new config to disable forking agnet processes and custom socket files.

But even if skywalking-php is not listening, we still need to fix the transmission socket and not let it generate randomly.

**Comment by jmjoy** [comment]
> But even if skywalking-php is not listening, we still need to fix the transmission socket and not let it generate randomly.

https://github.com/apache/skywalking-php/pull/113#issuecomment-2179848997

If this problem can be solved, then it is possible, but currently only a random socket file name can be generated.

**Comment by LeiZhang-Hunter** [comment]
> > But even if skywalking-php is not listening, we still need to fix the transmission socket and not let it generate randomly.
> 
> [#113 (comment)](https://github.com/apache/skywalking-php/pull/113#issuecomment-2179848997)
> 
> If this problem can be solved, then it is possible, but currently only a random socket file name can be generated.

I think
1. Add skywalking-php to listen to .sock configuration
2. Specify the location of the .sock file sent by span
I think skywalking-php needs this function

**Comment by LeiZhang-Hunter** [comment]
> > But even if skywalking-php is not listening, we still need to fix the transmission socket and not let it generate randomly.
> 
> [#113 (comment)](https://github.com/apache/skywalking-php/pull/113#issuecomment-2179848997)
> 
> If this problem can be solved, then it is possible, but currently only a random socket file name can be generated.

What are the problems with kill -USR2

**Comment by LeiZhang-Hunter** [comment]
> kill -USR2

Make a switch to make skywalking-php stop listening to the socket and only send. Is there a bug?

**Comment by LeiZhang-Hunter** [comment]
> > But even if skywalking-php is not listening, we still need to fix the transmission socket and not let it generate randomly.
> 
> [#113 (comment)](https://github.com/apache/skywalking-php/pull/113#issuecomment-2179848997)
> 
> If this problem can be solved, then it is possible, but currently only a random socket file name can be generated.

Make a switch to make skywalking-php stop listening to the socket and only send. Is there a bug?

**Comment by jmjoy** [comment]
> What are the problems with kill -USR2

Reload will cause a new agent process to start. If there is only one socket file path, multiple agent processes will listen to the same socket at the same time.

**Comment by jmjoy** [comment]
How about add `skywalking_agent.standalone_socket_file_path`? This options disable forking agnet processes and custom socket file.

**Comment by LeiZhang-Hunter** [comment]
> How about add `skywalking_agent.standalone_socket_file_path`? This options disable forking agnet processes and custom socket file.

Sending data uses bincode::serialize, but I think this will become complicated, so I gave up this solution.

**Comment by LeiZhang-Hunter** [comment]
> How about add `skywalking_agent.standalone_socket_file_path`? This options disable forking agnet processes and custom socket file.

Parsing bincode::serialize using C++ is not an easy task

**Comment by LeiZhang-Hunter** [comment]
I thought of a solution to solve the php-fpm -F problem

1. Remove libc::prctl (libc::PR_SET_PDEATHSIG, libc::SIGTERM);

2. Add pid lock to protect the uniqueness of the process, so that the startup process will not be restarted repeatedly

3. Fix the pid file location

After adding these three items, I solved this problem

**Comment by LeiZhang-Hunter** [comment]
I thought of a solution to solve the php-fpm -F problem

1. Remove libc::prctl (libc::PR_SET_PDEATHSIG, libc::SIGTERM);

2. Add pid lock to protect the uniqueness of the process, so that the startup process will not be restarted repeatedly

3. Fix the pid file location

After adding these three items, I solved this problem

**Comment by jmjoy** [comment]
> > How about add `skywalking_agent.standalone_socket_file_path`? This options disable forking agnet processes and custom socket file.
> 
> Parsing bincode::serialize using C++ is not an easy task

Will this result in the forked agent process still existing when php-fpm is exited normally?

**Pull request closed without merging**
