### PR TITLE
Add plugin for phpredis.

### PR DESCRIPTION
**Pull request by jmjoy**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Are you going to implement most TODO plugins and run 0.2.0 release?

**Comment by jmjoy** [comment]
> Are you going to implement most TODO plugins and run 0.2.0 release?

I think it is possible to release version 0.2.0. It has been a month since version 0.1.0 was released.

**Comment by wu-sheng** [comment]
Your call. I just realized there are a lot of changes made in one month.

**Comment by jmjoy** [comment]
@heyanlong Please review when you are free.

**Comment by heyanlong** [comment]
@jmjoy Why used component ID 11000, based as my know the 11000 is rust component ID

**Comment by heyanlong** [comment]
Component ID lists: https://github.com/apache/skywalking/blob/8c683a0b67c3a20ff382489ad298828f7995c201/oap-server/server-starter/src/main/resources/component-libraries.yml#L622

**Comment by jmjoy** [comment]
But I use COMPONENT_PHP_REDIS_ID, which is 7.

**Comment by heyanlong** [comment]
I'm mean is https://github.com/apache/skywalking-php/pull/29/files#diff-b22a9eadf4b761e70c8ca23a67fab3711c4ac568b18aaf7d7da88f07e4b0905cR693

**Comment by jmjoy** [comment]
My mistake, was fixed.

**Comment by wu-sheng** [comment]
You could refer this doc, https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-cache/.
Make sure the tags existed, then you can see the cache metrics on the UI's virtual cache dashboard.

**Comment by jmjoy** [comment]
@wu-sheng  I found that the code is `cache.cmd`, but the document is `cache.command`, which is correct?

https://github.com/apache/skywalking-java/blob/1ef7cb4117aad35bb5de0fb18f51813a455fd2b5/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/tag/Tags.java#L126

https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-cache/

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/master/oap-server/analyzer/agent-analyzer/src/main/java/org/apache/skywalking/oap/server/analyzer/provider/trace/parser/SpanTags.java#L44

Thanks for carefully checking. Please help on correcting doc.

**Comment by pg-yang** [comment]
Sorry,I would fix doc tonight

**Review by heyanlong — APPROVED** [review]

**Review by heyanlong — APPROVED** [review]

**Pull request merged**
