### PR TITLE
[docs] Update README

### PR DESCRIPTION
**Pull request by heyanlong**
Update README.md to add documentation, contact us etc. items.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please add milestone to every PR.

**Review by jmjoy — APPROVED** [review]
LGTM

**Comment by jmjoy** [comment]
> Please add milestone to every PR.

Can you help to create 0.1.0 milestone, I don't have permission.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-php/milestones

You can't create from here? I don't know there is a limitation.

**Comment by heyanlong** [comment]
I will add it @jmjoy

**Comment by jmjoy** [comment]
> https://github.com/apache/skywalking-php/milestones
> 
> You can't create from here? I don't know there is a limitation.

Sorry, I missed this. :cry:

**Pull request merged**
