### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by heyanlong**

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think we should keep compiling doc, because, in the release process, the PMC should check your source tar is able to compile passed or not.

Also, you should have a release doc about the steps, and scripts about how to package the release source tar and binary tar(licenses of dependencies and .so files) if you would provide a binary files.

**Comment by jmjoy** [comment]
I found `pecl` can install local package, so we can pack the code, and install it by `pecl install skywalking_agent-0.1.0.tgz`.

**Comment by wu-sheng** [comment]
> I found `pecl` can install local package, so we can pack the code, and install it by `pecl install skywalking_agent-0.1.0.tgz`.

Would this OS sensitive?

**Comment by jmjoy** [comment]
> > I found `pecl` can install local package, so we can pack the code, and install it by `pecl install skywalking_agent-0.1.0.tgz`.
> 
> Would this OS sensitive?

Linux and MacOS may work well, expect Windows.

**Comment by wu-sheng** [comment]
That should be good, let's build the scripts for the binary. Notice, we need LICENSE for binary dependencies. Rust side should be supported by skywalking-eyes, but I don't know about PHP/C/PHPer dependencies

**Review by jmjoy — APPROVED** [review]
OK, I will add the `pecl` package support later.

**Comment by wu-sheng** [comment]
As you have added menu file, please update the website doc setting accordingly. Then we could check how PHP docs work on preview.

**Pull request merged**
