### PR TITLE
Inject skywalking context.

### PR DESCRIPTION
**Pull request by jmjoy**
https://github.com/apache/skywalking/issues/11885

### CODE REVIEW

**Comment by wu-sheng** [comment]
Should we consider the whole trace context?

**Review by heyanlong — APPROVED** [review]

**Comment by jmjoy** [comment]
> Should we consider the whole trace context?

$serviceName, $instanceName, $traceId, $traceSegmentId are injected.

**Comment by wu-sheng** [comment]
> > Should we consider the whole trace context?
> 
> $serviceName, $instanceName, $traceId, $traceSegmentId are injected.

How about $spanId?

**Comment by wu-sheng** [comment]
And please update the docs according, after you added the span ID.

**Comment by jmjoy** [comment]
> How about $spanId?

$spanId should not be for the entire request, right?

**Comment by wu-sheng** [comment]
> > How about $spanId?
> 
> $spanId should not be for the entire request, right?

It is not. It is variable according to span creation and stop status.

**Comment by jmjoy** [comment]
> > $spanId should not be for the entire request, right?
> 
> It is not. It is variable according to span creation and stop status.

I would like to implement $spanId in the future (if there is user demand)

**Comment by wu-sheng** [comment]
> > > $spanId should not be for the entire request, right?
> > 
> > 
> > It is not. It is variable according to span creation and stop status.
> 
> I would like to implement $spanId in the future (if there is user demand)

If that is the case, please remove segmentId as well, that is useless without span ID. Both IDs lock the specific span.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
